### ISSUE TITLE
找不到包

### ISSUE THREAD

**Issue by AbrahamCaiJin** [whaiming/brush-csdn-traffic#1]
import static whm.brush.csdnandcnblogs.JsoupGetArticleUrl.getCsdnBlogsUrl;
import static whm.brush.csdnandcnblogs.JsoupGetArticleUrl.getDoc;
请问这两个是需要什么包呀？

**Comment by AbrahamCaiJin** [comment]
能运行了，但还是刷不了？大佬指导我一下吧

**Comment by AbrahamCaiJin** [comment]
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=503, URL=http://blog.csdn.net/u014727709/article/details/77896286
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:590)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:540)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:227)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:216)
	at JsoupGetArticleUrl.getDoc(JsoupGetArticleUrl.java:74)
	at JsoupGetIp.visit(JsoupGetIp.java:81)
	at JsoupGetIp$1.run(JsoupGetIp.java:114)
	at java.lang.Thread.run(Unknown Source)

**Comment by whaiming** [comment]
不好意思今天才看到，最近比较忙都没上来看过了，我就是Jsoup刷的哈，这是个maven项目，可以自动下载依赖包的
